# Generated by Django 4.2.2 on 2023-06-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='contacto',
        ),
        migrations.AddField(
            model_name='tareas',
            name='contacto',
            field=models.ManyToManyField(to='contacto.contacto'),
        ),
    ]
