# Generated by Django 4.2.2 on 2023-06-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_remove_tareas_contacto_tareas_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
