# Generated by Django 4.2.2 on 2023-06-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_alter_contacto_user'),
        ('tareas', '0003_tareas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='contacto',
            field=models.ManyToManyField(related_name='tareas', to='contacto.contacto'),
        ),
    ]
