# Generated by Django 4.1.1 on 2023-05-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
