# Generated by Django 4.1.1 on 2023-05-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
