# Generated by Django 3.2.12 on 2023-10-31 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_rename_fk_id_perfil_gastos_fk_id_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
