# Generated by Django 3.2.12 on 2023-11-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_gastos_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
